---
- name: Gather system information
  hosts: all
  # hosts: '{{ target }}' inventory add: [target_group] host1 ansible_host=IP
  tasks:
    - name: Display hostname
      ansible.builtin.command: hostname
      register: hostname_output

    - name: Display /etc/hosts content
      ansible.builtin.command: cat /etc/hosts
      register: hosts_output

    - name: Display system timezone
      ansible.builtin.command: timedatectl | grep Timezone
      register: timezone_output

    - name: Display current date and time
      ansible.builtin.command: date
      register: date_output

    - name: Display netplan configuration
      ansible.builtin.command: cat /etc/netplan/*.yaml
      register: netplan_output

    - name: Display netplan configuration (if /etc/netplan/*.yaml does not exist)
      ansible.builtin.command: cat /etc/netplan/*.yml
      register: netplan_output_alt
      ignore_errors: yes

    - name: Output gathered information
      ansible.builtin.debug:
        msg: |
          Hostname: {{ hostname_output.stdout }}
          /etc/hosts content:
          {{ hosts_output.stdout }}
          Timezone: {{ timezone_output.stdout }}
          Date: {{ date_output.stdout }}
          Netplan configuration:
          {% if netplan_output.stdout %}
          {{ netplan_output.stdout }}
          {% elif netplan_output_alt.stdout %}
          {{ netplan_output_alt.stdout }}
          {% else %}
          No netplan configuration found.
          {% endif %}
